### ISSUE TITLE
Visible Events

### ISSUE THREAD

**Issue by Wintermourn** [NuclearCheese/rabiribi_editor#31]
The ability to see where events are is pretty important. It would be useful to at least have a box showing where events are, as well as the ability to mouse over the event to get the name and/or the ID. Unless my computer's broken and I just can't see the events.

**Comment by NuclearCheese** [comment]
Event IDs are visible, but only as a simple text.  There are certainly improvements which can be made, including your idea of showing a box where event IDs currently are.
Another thought I had was an option to configure the text color/size/etc that events are displayed in, which may help make them more visible.  If we can get outlined text, that could help even more.

**Comment by Wintermourn** [comment]
Would it be possible to have a "spritesheet" loaded at all times that would just be a box? For example: 
![image](https://user-images.githubusercontent.com/24772618/34457949-d5c9402c-ed86-11e7-9ec5-d889afaffadb.png)
The blue E would be used for events like dialog or boss battles, the purple(ish) E would be used for entities, and the Yellow I would be used to show the location of items. Mousing over the icons would show you details on the object, like the name and ID. 

I'm not that good with C#, so I don't know how difficult these would be.

**Comment by NuclearCheese** [comment]
I like this idea, and I don't think it'll be hard to implement.  I do think the tiles will need to be a bit different looking - mainly to make the lines bulkier so they don't get too distorted when zooming out.  I also think a few more colors can be selected for various entity types:
music triggers
tile entities
warp entities
environment entities
unknown entities (ones the editor doesn't have a definition for)

Thanks for the suggestion.  I'll hopefully be able to get this implemented soon.

**Comment by NuclearCheese** [comment]
Alright, here's what a first pass at this looks like.  Let me know if you have any feedback, please.

![image](https://user-images.githubusercontent.com/32045777/34464926-53942714-ee64-11e7-9bc7-9503132630d3.png)

I also included an option to toggle between the icons being transparent and fully opaque, as pictured below.  Note that if an event and item overlap, the opaque icons get split in half so you can still see both.

![image](https://user-images.githubusercontent.com/32045777/34464930-6d5a88c8-ee64-11e7-93f8-98567c6e7429.png)

If you have a setup to build the editor, you can try it out yourself by pulling from the "new_event_icons" branch.  Use the new drop-down menus in the upper-right to change how event and icons are shown.


Another item asked about above is the ability to mouse over something and get the name and ID.  ID already gets shown in the info pane in the View tab, but no name yet.  I can look at adding that functionality in, although it may not be perfect (for one example, I just realized that event ID 250 has two different meanings - easter eggs and warp modifiers).

**Comment by NuclearCheese** [comment]
Alright, I've added display of event and item names to the info pane of the View tab.  I've put together a prerelease of v0.6 so that these updates can be tested out - feel free to give it a go and leave any feedback.
[https://github.com/NuclearCheese/rabiribi_editor/releases/tag/v0.6-pre](https://github.com/NuclearCheese/rabiribi_editor/releases/tag/v0.6-pre)

**Comment by Wintermourn** [comment]
Here's something interesting: When I removed some events, they would sometimes leave lines. They disappear after changing the zoom level, but it's still a bit odd. I tried it with music events here.
![image](https://user-images.githubusercontent.com/24772618/34630944-cd107994-f233-11e7-8d56-ca309f0e6634.png)
Edit: This happens with most tiles :(

**Comment by NuclearCheese** [comment]
Thanks for the report.  I can recreate it myself, and it looks like it applies to all layers.  I've created a new issue for this: #38

**Comment by NuclearCheese** [comment]
I've released the full v0.6 ( at [https://github.com/NuclearCheese/rabiribi_editor/releases/tag/v0.6](https://github.com/NuclearCheese/rabiribi_editor/releases/tag/v0.6) ) which includes the event icons.  Since I didn't get any further reports of issues with the functionality, I'm going to assume it's good and close this issue.  Thanks again for bringing it up.
